#!/bin/sh

# Prerequisite: Check linux OS = centos 7 
if [ -f '/etc/centos-release' ]; then
    OSVER=`sed 's/.*release \([0-9]*\).*/\1/' /etc/centos-release `
    echo "Found CENTOS $OSVER"
else
   echo "Error: can only be run on CENTOS 7"
   exit -1
fi

# 1. Install certbot
echo "Installing certbot"
./install_certbot

# 2. Get let's encrypt certificate
echo "Get ssl certificate - not implemented"
#./get_ssl_cert

# 3. Install nginx
echo "Installing nginx"
./install_nginx

# 4. Configure nginx
echo "Configure nginx - not implemented"
#./config_nginx

# 5. Install exim
echo "Installing exim"
./install_exim

# 6. Configure exim
echo "Configure exim  - not implemented"
#./config_exim

# 7. Install mariadb
echo "Install mariadb - not implemented"
#./install_mariadb

# 8. Configure mariadb
echo "Configure mariadb - not implemented"
#./config_mariadb

# 9. Done
echo "Done"
read -n 1 -s -r -p "Press any key to continue..."
echo ""
