#!/usr/bin/env bash
if [ `id -u` != 0 ]; then
  echo "Error: install_python3 must be executed by root"
  exit -1
fi

yum -y install epel-release
yum -y install python36 python36-pip
ln -s /usr/bin/python3.6 /usr/bin/python3
