#!/usr/bin/env bash
if [ `id -u` != 0 ]; then
  echo "Error: install_exim must be executed by root"
  exit -1
fi

yum -y install epel-release
yum -y install exim

# Don't start and enable exim until configuration has been done.
#systemctl enable exim
#systemctl start exim
#systemctl stop exim
